name: Plan / Test On PR

on:
  pull_request:
    branches:
      - main
## workflows called
jobs:
  push-on-pullrequest:
    uses: jbenaventem/wkf-terraform/.github/workflows/terraform-ci.yml@feat/reusable-workflow-tf
    with:
      version: "1.1.6"
      runs-on: "ubuntu-latest"
  tf-sec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif         

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif

      - name: Comments On Pull Request
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  




