name: Plan / Test On PR

on:
  pull_request:
    branches:
      - main

jobs:
  push-on-pullrequest:
    uses: santander-group-cto/wkf-terraform/.github/workflows/terraform-ci.yml@feat/reusable-workflow-tf
    with:
      version: "1.1.6"
      runs-on: "ubuntu-latest"


